parameters:
- name: projectName
  type: string
- name: dotnetVersion
  type: string
  default: '8.x'
- name: buildConfiguration
  type: string
  default: 'Release'
- name: poolName
  type: string
  default: 'self-hosted'

jobs:
  - job: Build
    pool: ${{ parameters.poolName }}
    steps:
      - checkout: self
        fetchDepth: 0
      - task: UseDotNet@2
        inputs:
          version: ${{ parameters.dotnetVersion }}
      - task: DotNetCoreCLI@2
        displayName: "Install Fantomas tool"
        inputs:
          command: 'custom'
          custom: 'tool'
          arguments: 'install -g fantomas'
      - task: Bash@3
        displayName: "Run Fantomas check"
        inputs:
          targetType: 'inline'
          script: |
            fantomas "src/${{ parameters.projectName }}" --check
      - task: DotNetCoreCLI@2
        name: Restore
        inputs:
          command: 'restore'
          projects: 'src/${{ parameters.projectName }}/*.fsproj'
      - task: DotNetCoreCLI@2
        name: Build
        inputs:
          command: 'build'
          projects: 'src/${{ parameters.projectName }}/*.fsproj'
          arguments: '-c ${{ parameters.buildConfiguration }}'
      - task: DotNetCoreCLI@2
        name: Pack
        inputs:
          command: 'pack'
          packagesToPack: 'src/${{ parameters.projectName }}/${{ parameters.projectName }}.fsproj'
          nobuild: true
      - task: PublishPipelineArtifact@1
        name: Publish
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'drop'
  - deployment: Deploy
    environment: prd
    pool:
      vmImage: 'windows-latest'
    dependsOn: Build
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: drop
            - task: NuGetCommand@2
              displayName: 'Push to NuGet.org'
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/drop/*.nupkg'
                nuGetFeedType: 'external'
                publishFeedCredentials: 'nuget'
