<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <DisableImplicitLibraryPacksFolder>true</DisableImplicitLibraryPacksFolder>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\otsom.fs.Bot\otsom.fs.Bot.fsproj"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Builders.fs"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1"/>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2"/>
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.1"/>
  </ItemGroup>

</Project>
