trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/otsom.fs.Resources/*

pr:
  branches:
    include:
      - main
  paths:
    include:
      - src/otsom.fs.Resources/*

extends:
  template: /azure-pipelines.template.yml
  parameters:
    projectName: 'otsom.fs.Resources'
