trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/otsom.fs.OAuth.Telegram/*

pr:
  branches:
    include:
      - main
  paths:
    include:
      - src/otsom.fs.OAuth.Telegram/*

extends:
  template: ../../azure-pipelines.template.yml
  parameters:
    projectName: 'otsom.fs.OAuth.Telegram'
